### ISSUE TITLE
Continue play audio upon lock screen

### ISSUE THREAD

**Issue by kontrollanten** [mister-ben/videojs-mobile-ui#10]
Thanks for this plugin! Have you considered add support for continue play audio (if available, otherwise lowest video quality) upon locking the screen?

**Comment by mister-ben** [comment]
Just did a quick test, and was actually surprised to see that loading an audio-only src and calling play() on the document's visibilitychange event works when the screen locks, on Android Chrome at least. So changing source, seeking, playing on visibility changes might be feasible. I don't know that it should necessarily be implemented within this plugin though.

**Comment by kontrollanten** [comment]
Impressive quick!

> I don't know that it should necessarily be implemented within this plugin though.

What else options do you see? A part of videojs or a separate plugin?
