### ISSUE TITLE
Docs unclear in setup

### ISSUE THREAD

**Issue by EpicNicks** [mister-ben/videojs-mobile-ui#11]
using: create-react-app

I spent some time trying to figure out how to use the component when upon inspection the mobile controls div was not covering the video.
This was fixed upon finding and importing videojs-mobile-ui/dist/videojs-mobile-ui.css
Is this intended and the docs unclear or is this a react issue?

Also, it is unclear how the default options can be overriden.

**Comment by silaas** [comment]
You can try overriding the default options when initializing the plugin as
```
player.mobileUi({
  fullscreen: {
    enterOnRotate: true,
    exitOnRotate: true,
    lockOnRotate: true,
    alwaysInLandscapeMode: true,
  },
  touchControls: {
    seekSeconds: 10,
    tapTimeout: 300,
    disableOnEnd: false
  }
});

```

**Comment by mister-ben** [comment]
Added some explicit text to the readme that the CSS is required. Thanks for the feedback.
