### ISSUE TITLE
Rotation options not working on mobile

### ISSUE THREAD

**Issue by EpicNicks** [mister-ben/videojs-mobile-ui#12]
using: create-react-app

Touch controls all work properly but the video does not enter/exit fullscreen on rotation. Tried in chrome dev tools as well as on a hard phone.

**Comment by silaas** [comment]
We have forked this repo and made some improvements as well and fixed the bugs. Try using the forked [version](https://github.com/silaas/videojs-mobile-ui) until the author himself resolves the issues in the main repo. We have also published npm [package](https://www.npmjs.com/package/@silaas/videojs-mobile-ui) of this forked version. Hope it helps you.

**Comment by mister-ben** [comment]
Sorry, I thought I'd done this already but realise it got caught up with some other updates I wanted to get out but put on hold. I'll release a version with that soon.

@silaas pull requests are welcome if you have other suggestions.
