### ISSUE TITLE
Tablet orientation not working correctly

### ISSUE THREAD

**Issue by Alpha-Buchotep** [mister-ben/videojs-mobile-ui#15]
Hi there Guys!

I am using videojs in a self-created framework .I have installed the videojs-mobile-ui plugin but the rotate function not working corrently. Tablet screen resolution is 1920x1200 pixel. Usually I am using my tablet in landscape orientation. No matters how I rotate the tablet it goes to fullscreen only in portrait mode. My Androd phones not affected by this problem.

I "hacked" this issue with the following modifications and the rotation problem is gone. It works on all mobile and tablet devices.

Is there any side effect of this modification?

Thank you in advance for your answers.

```javascript
 
  var rotationHandler = function rotationHandler() {
    var currentAngle = angle();

	//---------------------------------------------------------------------
	// Orientation check
	// Link: https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation
	//---------------------------------------------------------------------

	var orientation = (screen.orientation || {}).type || screen.mozOrientation || screen.msOrientation;	

    //if ((currentAngle === 90 || currentAngle === 270 || currentAngle === -90) && options.fullscreen.enterOnRotate) {
   	if (orientation === "landscape-primary" || orientation === "landscape-secondary" && options.fullscreen.enterOnRotate) {  
	  if (player.paused() === false) {
        player.requestFullscreen();
        if (options.fullscreen.lockOnRotate && screen.orientation && screen.orientation.lock) {
          screen.orientation.lock('landscape').then(function () {
            locked = true;
          }).catch(function () {
            videojs.log('Az orientáció zárolása nem engedélyezett');
          });
        }
      }
    }

    //if ((currentAngle === 0 || currentAngle === 180) && options.fullscreen.exitOnRotate) {	
	if (orientation === "portrait-secondary" || orientation === "portrait-primary" && options.fullscreen.exitOnRotate) {
      if (player.isFullscreen()) {
        player.exitFullscreen();
      }
    }
  };
```

**Comment by mister-ben** [comment]
That won't work on iOS which only supports `window.orientation`. There's a simpler fix that will not break compatibility, I'll add that.

**Comment by mister-ben** [comment]
Would you be able to verify that #17 works on your tablet?

**Comment by Alpha-Buchotep** [comment]
You're lightning fast! Thank You!

Cache cleared, refresh more than twice,... no luck.

It doesn't work on my tablet. (Sony Tablet Z, Android 5.1.1, Navitel T500 > 1280x800, Android 7)

One thing changed:  if I rotate the tablett from landscape to portrait the player goes landscape oriented fullscreen but 2 seconds later will exit.

Maybe separate functions will help? One for iOS and another for Anroid? 

I can write it.

**Comment by mister-ben** [comment]
Is that using the change in that branch? Its not merged or published to npm.

I've tested on the only tablet available to me now, Galaxy Tab on Browserstack, and that works correctly. `window.orientation`, `screen.orientation.angle` and `screen.orientation.type` are all correct. What does `screen.orientation.onchange = function() { console.log(window.orientation, window.screen.orientation.angle, window.screen.orientation.type); };` log on your tablets?

**Comment by Alpha-Buchotep** [comment]
Yes it uses Your fix #17. 

I cant acces to the console right now. I'll try it later.

My temporary fix is working but it's ugly:

```javascript

	//---------------------
	// iOS
	//---------------------

	if (videojs.browser.IS_IOS) {

		if ((currentAngle === 90 || currentAngle === 270 || currentAngle === -90) && options.fullscreen.enterOnRotate) {
		  if (player.paused() === false) {
			player.requestFullscreen();
			if (options.fullscreen.lockOnRotate && screen.orientation && screen.orientation.lock) {
			  screen.orientation.lock('landscape').then(function () {
				locked = true;
			  }).catch(function () {
				videojs.log('Az orientáció zárolása nem engedélyezett');
			  });
			}
		  }
		}
	}
	
	if (videojs.browser.IS_IOS) {

		if ((currentAngle === 0 || currentAngle === 180) && options.fullscreen.exitOnRotate) {	
		  if (player.isFullscreen()) {
			player.exitFullscreen();
		  }
		}
	}

	//---------------------
	// Android
	//---------------------

	if (videojs.browser.IS_ANDROID) {

		if (orientation === "landscape-primary" || orientation === "landscape-secondary" && options.fullscreen.enterOnRotate) {  
		  if (player.paused() === false) {
			player.requestFullscreen();
			if (options.fullscreen.lockOnRotate && screen.orientation && screen.orientation.lock) {
			  screen.orientation.lock('landscape').then(function () {
				locked = true;
			  }).catch(function () {
				videojs.log('Az orientáció zárolása nem engedélyezett');
			  });
			}
		  }
		}
	}		
		

	if (videojs.browser.IS_ANDROID) {

		if (orientation === "portrait-secondary" || orientation === "portrait-primary" && options.fullscreen.exitOnRotate) {
		  if (player.isFullscreen()) {
			player.exitFullscreen();
		  }
		}
	}

```

**Comment by Alpha-Buchotep** [comment]
Update

`screen.orientation.onchange = function() { console.log(window.orientation, window.screen.orientation.angle, window.screen.orientation.type); };` console log results

```javascript
ƒ () { console.log(window.orientation, window.screen.orientation.angle, window.screen.orientation.type); }
VM137:1 -90 270 "portrait-primary"
VM137:1 0 0 "landscape-primary"
VM137:1 90 90 "portrait-secondary"
VM137:1 180 180 "landscape-secondary"
```

**Comment by mister-ben** [comment]
Thanks. That really doesn't make sense then, as your browser is settings `window.orientation` correctly...

**Comment by Alpha-Buchotep** [comment]
Do You have any suggestion? Normal (primary) landscape mode is 0 0.  This means player.exitFullScreen, right? 
The ugly "hotfix" is working correctly. I don't have an iPhone, but it's working in the developer tools.

**Comment by mister-ben** [comment]
Ah the penny's just dropped that your tablet's 0° is landscape. It makes sense now. It will just need a little refactor to prefer the string and fall back to the angle in that case.

**Comment by Alpha-Buchotep** [comment]
Sounds good. This is a good old Sony Tablet Z with 1920x1200 pixel resolution display, Android 5.1.1. Tested in latest Chrome, Firefox and Dolphin browsers.

**Comment by mister-ben** [comment]
Updated #17 to use the type when available over angle. Could you check the behaviour on your tablet?

**Comment by Alpha-Buchotep** [comment]
Thanx, I'll check it soon.

**Comment by Alpha-Buchotep** [comment]
Some typo was in the code. I fixed and tried it, but it doesn't work on the tablet. Similar to the first behaviour. Only portrait mode fullscreen. 

Maybe I mistyped something. This was a long running day for me, so I think I'll lay down and get a little bit of sleep.

Thanks for Your help!

**Comment by Alpha-Buchotep** [comment]
Everything works as expected! Thank you for Your help and support.
