### ISSUE TITLE
Touch Controls Bypassing Ads in videojs-mobile-ui

### ISSUE THREAD

**Issue by renatosalopes** [mister-ben/videojs-mobile-ui#150]
Hi,

I'm using videojs-mobile-ui v1.1.0, video.js v8.5.2, and videojs-contrib-ads v7.3.2 in my player setup. I've implemented a custom plugin that enables ads to be shown during prerolls, midrolls, and postrolls. However, I've noticed that Mobile UI's touch controls can bypass ads before they are completely displayed. 

Is there any way to enable or disable touch controls through a listener or some other mechanism? It would be great to have better control over the user interaction during ad playback to ensure that ads are displayed fully as intended.

Thank you for your assistance!

Best regards,
Renato

**Comment by mister-ben** [comment]
Does #151 work for you? That would just hide the overlay during ad playback.

Also, `player.touchOverlay.hide()` and `player.touchOverlay.show()` could be used to hide and re-display it.

**Comment by renatosalopes** [comment]
Yes, #151 works for me. It effectively hides the overlay during ad playback. Thanks for the solution!
