### ISSUE TITLE
Playback rate button hidden

### ISSUE THREAD

**Issue by andreifilip123** [mister-ben/videojs-mobile-ui#164]
Hello and thank you for this nice plugin. 

Is the playback rate button hidden by mistake or by choice ? On iOS, I know the playback rate is shown when the video is open but I'd still like for consistency to have the playback rate button show on the video player when not open.
Also, related to https://github.com/videojs/video.js/issues/8176 in the other repo, is there any way to show custom added children in the video on ios ? (I'm pretty sure not but worth asking anyway).

Thanks!

**Comment by mister-ben** [comment]
Sorry, I'm not sure what you mean. This plugin doesn't do anything with the standard playback rates control.

Regarding showing custom controls or overlays on iPhone Safari in fullscreen, it will not possible until Apple implements the standard full screen API, and there's no sign they are planning to do so. You can use Video.js's [preferFullWindow](https://videojs.com/guides/options/#preferfullwindow) option, but that is not true full screen, it's a compromise that just expands the player to fill the browser window.

**Comment by andreifilip123** [comment]
Oh, sorry, I thought this controls everything mobile related. Still, is there any way to show the playback rate control on mobile ? Currently it's hidden

**Comment by mister-ben** [comment]
Nothing special is needed on a basic player setup to show the playback rates control on mobile. It will be displayed if `playbackRates` have been configured, the same as on desktop. If you're having trouble wiht this, please open an issue on the video.js repo with a reproducible test.
