### ISSUE TITLE
What is the different between enteronrotate and lockonrotate?

### ISSUE THREAD

**Issue by ImPeekaboo** [mister-ben/videojs-mobile-ui#169]
Im not get it
Sorry for my question

**Comment by ImPeekaboo** [comment]
Will close this

**Comment by mister-ben** [comment]
`enterOnRotate` = enter fullscreen when the device is rotated
`enterOnRotate` + `lockOnRotate` enter fullscreen when the device is rotated, and lock the screen orientation
