### ISSUE TITLE
TouchOverlay  main div ".vjs-touch-overlay" is covering ControlBar (".vjs-control-bar")

### ISSUE THREAD

**Issue by pPanda-beta** [mister-ben/videojs-mobile-ui#2]
Hi,
Although touch overlay gives some of the import player controls using touch, control bar still needs to be accessed for complete functionalities and to interact with elements of other 3rd party plugins.

A quick hack to solve the problem : 
Setting z-index of control bar so that it comes above touch overlay, and absorbs events prior.
`
	.vjs-control-bar {
		z-index: 1;
	}
`

**Comment by mister-ben** [comment]
The control bar should already be on top of the overlay. It comes after in in the dom. With which browser do you have a problem?

**Comment by pPanda-beta** [comment]
This is verified on mobile chrome.
Also to debug this on desktop chrome **please turn on "Toggle device toolbar" and select any of the mobile.** 

+ Here is a small code to reproduce the problem
Try it right now ![using data url](data:text/html;charset=utf-8;base64,PGh0bWw+DQo8aGVhZD4NCgk8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMCIvPg0KDQoJPGxpbmsgaHJlZj0iaHR0cHM6Ly92anMuemVuY2RuLm5ldC83LjYuNS92aWRlby1qcy5jc3MiIHJlbD0ic3R5bGVzaGVldCIgY3Jvc3NvcmlnaW49ImFub255bW91cyIvPg0KCTxzY3JpcHQgc3JjPSJodHRwczovL3Zqcy56ZW5jZG4ubmV0LzcuNi41L3ZpZGVvLmpzIiBjcm9zc29yaWdpbj0iYW5vbnltb3VzIj48L3NjcmlwdD4NCg0KCTxsaW5rIGhyZWY9Imh0dHBzOi8vdW5wa2cuY29tL3ZpZGVvanMtbW9iaWxlLXVpQDAuNC4xL2Rpc3QvdmlkZW9qcy1tb2JpbGUtdWkuY3NzIiByZWw9InN0eWxlc2hlZXQiDQoJCSAgY3Jvc3NvcmlnaW49ImFub255bW91cyIvPg0KCTxzY3JpcHQgc3JjPSJodHRwczovL3VucGtnLmNvbS92aWRlb2pzLW1vYmlsZS11aUAwLjQuMS9kaXN0L3ZpZGVvanMtbW9iaWxlLXVpLm1pbi5qcyINCgkJCWNyb3Nzb3JpZ2luPSJhbm9ueW1vdXMiPjwvc2NyaXB0Pg0KDQo8L2hlYWQ+DQoNCjxib2R5IGFsaWduPSJjZW50ZXIiPg0KPHZpZGVvIGlkPSd2aWRlby1wbGF5ZXInIGNsYXNzPSd2aWRlby1qcyB2anMtZGVmYXVsdC1za2luJyBjb250cm9scyBwcmVsb2FkPSdhdXRvJw0KCSAgIHN0eWxlPSJ3aWR0aDogMTAwJTsgaGVpZ2h0OiAxNXJlbSI+DQoJPHNvdXJjZSBzcmM9Imh0dHBzOi8vdmpzLnplbmNkbi5uZXQvdi9vY2VhbnMubXA0Ii8+DQo8L3ZpZGVvPg0KDQo8c2NyaXB0Pg0KCXZpZGVvanMoJ3ZpZGVvLXBsYXllcicpLm1vYmlsZVVpKCk7DQo8L3NjcmlwdD4NCg0KPC9ib2R5Pg0KDQo8L2h0bWw+)

```html
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

	<link href="https://vjs.zencdn.net/7.6.5/video-js.css" rel="stylesheet" crossorigin="anonymous"/>
	<script src="https://vjs.zencdn.net/7.6.5/video.js" crossorigin="anonymous"></script>

	<link href="https://unpkg.com/videojs-mobile-ui@0.4.1/dist/videojs-mobile-ui.css" rel="stylesheet"
		  crossorigin="anonymous"/>
	<script src="https://unpkg.com/videojs-mobile-ui@0.4.1/dist/videojs-mobile-ui.min.js"
			crossorigin="anonymous"></script>

</head>

<body align="center">
<video id='video-player' class='video-js vjs-default-skin' controls preload='auto'
	   style="width: 100%; height: 15rem">
	<source src="https://vjs.zencdn.net/v/oceans.mp4"/>
</video>

<script>
	videojs('video-player').mobileUi();
</script>

</body>

</html>

```

**Comment by bcbclifford** [comment]
Odd, the overlay does end up after the control bar in your example. Not sure why yet.

**Comment by mister-ben** [comment]
It's to do with how `addChild` works in Video.js. It doesn't account for exisitng components that don't have DOM elements. See videojs/video.js/pull/6297

**Comment by mister-ben** [comment]
Resolved in Video.js
