### ISSUE TITLE
Event listener does not get removed when player is disposed

### ISSUE THREAD

**Issue by hunterjm** [mister-ben/videojs-mobile-ui#20]
Currently calling `player.dispose()` and creating a new instance (think SPA) causes an additional `rotationHandler` to be [added to the event listener stack](https://github.com/mister-ben/videojs-mobile-ui/blob/master/src/plugin.js#L111), but the old `rotationHandler` with a reference to the already disposed player never gets removed. This causes the `rotationHandler` to error out on [the first call to `player`](https://github.com/mister-ben/videojs-mobile-ui/blob/master/src/plugin.js#L90).

**Comment by mister-ben** [comment]
Good point, that should be removed.
