### ISSUE TITLE
[Feature] `enterFullscreen` function

### ISSUE THREAD

**Issue by rtritto** [mister-ben/videojs-mobile-ui#28]
I need an exported function that enter to fullscreen, rotate screen to 'landscape' and update `locked` state variable to true.

## Example
I want to add enter to fullscreen on 'play' event.

Is needed an exported function in file `src/plugin.js`:
```js
export const enterFullscreen = async (player, orientation) => {
  player.requestFullscreen();
  await screen.orientation.lock(orientation).then(() => {
    locked = true;
  }).catch((e) => {
    videojs.log('Browser refused orientation lock:', e);
  });
}
```
So I can use that function on `play` event.
```js
player.on('play', async () => {
  if (!player.isFullscreen()) {
    await enterFullscreen(player, 'landscape');
  }
})
```

## Impacts in file `src/plugin.js`
1. Move `locked` variable to global
2. Create and export `enterFullscreen` function

**Comment by sbbullet** [comment]
I think we can now close this issue @rtritto, right? We have updated the package with a new feature that you can use as specified in #49 for your case. Thank you!
