### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ert55** [mister-ben/videojs-mobile-ui#3]
Player won't go fullscreen on rotate. I'm using default plugin options.  Tested in firefox on an old samsung galaxy s2. 
videojs.browser.IS_ANDROID returns true so a mobile device is detected properly.

**Comment by mister-ben** [comment]
It works on Firefox on a modern phone. If it doesn't work on such an old device, it's probably just a limitation of the Android version and/or Firefox version that will run on it.
