### ISSUE TITLE
`video.js` should be a peer dependency

### ISSUE THREAD

**Issue by rtritto** [mister-ben/videojs-mobile-ui#34]
`video.js` should be moved from *dependencies* to *peerDependencies*.

[Source](https://github.com/videojs/video.js/issues/7068):

>figure out plugins
>- Video.js should probably be a peer dependency
>- plugins probably shouldn't register themselves automatically and probably get Video.js via DI

**Comment by rtritto** [comment]
@mister-ben any update?

**Comment by mister-ben** [comment]
It could be a peerDependency _and_ devDependency, but https://github.com/videojs/videojs-generator-verify would have to install peerDependencies during its test.
