### ISSUE TITLE
[BUG] Fullscreen enter on rotate not working

### ISSUE THREAD

**Issue by ceferrari** [mister-ben/videojs-mobile-ui#36]
The fullscreen enter on rotate feature is not working as expected. It seems the be some flaw with the precedence logic on the `orientationString` variable:

- https://github.com/mister-ben/videojs-mobile-ui/blob/master/src/plugin.js#L33

```
const orientationString = (screen.orientation || {}).type || screen.mozOrientation || screen.msOrientation || ''.split('-')[0];
```
Adding parentheses at the beginning and before the `.split` part fixed it for me:
```
const orientationString = ((screen.orientation || {}).type || screen.mozOrientation || screen.msOrientation || '').split('-')[0];
```
@mister-ben

**Comment by mister-ben** [comment]
Thanks, you're right
