### ISSUE TITLE
TypeError: player.mobileUi is not a function

### ISSUE THREAD

**Issue by vasaf** [mister-ben/videojs-mobile-ui#38]
Previous issue is closed, but I believe this is a current issue. Running `video.js 7.0.0` Tried `6.13` and `7.17`

Tried registering plugin - No luck

Tried importing `videojs-mobile-ui/dist/videojs-mobile-ui` / `videojs-mobile-ui`

Tried importing `import mobileUi videojs-mobile-ui`

Any help would be appreciated. Thanks

**Comment by raphaelsaunier** [comment]
I hope you've been able to solve this issue by now, but in case anyone else lands here, I ran into the same issue today and it took me a while to figure out that `videojs-mobile-ui` was loading a different version of `video.js` than the parent project.

Removing the specific patch version from `package.json` (in my case replacing `7.15.4` with `^7`) and letting Yarn resolve the latest version (`7.18.1` as of this writing) with a `yarn install` solved the problem for me.
