### ISSUE TITLE
Installation for non-Node/React platforms

### ISSUE THREAD

**Issue by syscafedevelopment** [mister-ben/videojs-mobile-ui#5]
What are the needed files for using this in an ASP.NET MVC site? Since npm is not used, I can only include js/css files. Which one should I include?

**Comment by mister-ben** [comment]
Grabbing dist files from a CDN such as unpkg or jsdelivr is simplest if you just want URLs, e.g.

https://unpkg.com/browse/videojs-mobile-ui@0.4.1/dist/videojs-mobile-ui.css
https://unpkg.com/browse/videojs-mobile-ui@0.4.1/dist/videojs-mobile-ui.min.js

**Comment by ccabrol** [comment]
Can you add videojs-mobile-ui@0.5.2 to a CDN?

**Comment by mister-ben** [comment]
It's already available e.g. https://unpkg.com/videojs-mobile-ui@0.5.2/dist/videojs-mobile-ui.min.js
