### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rtritto** [mister-ben/videojs-mobile-ui#55]
Any update for a new release? (_npm_ version is locked to _0.8.0_)

**Comment by rtritto** [comment]
@mister-ben any update for a release of `next` branch (support `video.js` _v8.0.0-rc1_)?

**Comment by rtritto** [comment]
Version _1.0.0_, with support of video.js v8, is out, thanks!

**Comment by samal-rasmussen** [comment]
`npm install videojs-mobile-ui` gave me v 0.7.0 though I can definitely see that 1.0.1 has been released:

https://www.npmjs.com/package/videojs-mobile-ui?activeTab=versions
https://github.com/mister-ben/videojs-mobile-ui/blob/master/CHANGELOG.md

I was able to get 1.0.1 by updating to it in package.json by hand and rerunning `npm install`.
