### ISSUE TITLE
TypeError: player.mobileUi is not a function - React JS

### ISSUE THREAD

**Issue by VAIBHAV7500** [mister-ben/videojs-mobile-ui#6]

**Comment by BenevidesLecontes** [comment]
I'm having this issue too

**Comment by mister-ben** [comment]
You might need to register the plugin in React

    if (!this.hasPlugin('mobileUi')) {
      videojs.registerPlugin('mobileUi', mobileUi);
    } 
    this.mobileUi();

**Comment by earlpeterg** [comment]
something like this worked for me. You should import it after the videojs reference.
```
import videojs from 'video.js';
import 'videojs-mobile-ui';
```

**Comment by benbro** [comment]
I have the same issue. Couldn't find a way to make it automatically register the plugin in a plain js webpack 4.3.0 project.
When I register the plugin manually I'm getting a new error:
```
Component TouchOverlay does not exist
```

```javascript
import videojs from 'video.js';
import mobileUi from 'videojs-mobile-ui';

videojs.registerPlugin('mobileUi', mobileUi);
let player = videojs('video');
player.mobileUi();
```

**Comment by earlpeterg** [comment]
Try `import 'videojs-mobile-ui';` or `import * from 'videojs-mobile-ui';`.

**Comment by benbro** [comment]
I've tried all possible forms. Still getting player.mobileUi is not a function.

**Comment by benbro** [comment]
I don't know why but it works If I copy the file from node_modules/videojs-mobile-ui/dist/videojs-mobile-ui.js to my src folder and import with:
```javascript
import videojs from 'video.js';
import './videojs-mobile-ui.js';
```

**Comment by kokins** [comment]
Same issue is here and function forceForTesting is not found.
The suggestion about .js file copy helped.

**Comment by hanya-0323** [comment]
> 此处存在相同问题，未找到功能forceForTesting。
> 有关.js文件复制的建议有所帮助。

player.mobileUi({});   you should add empty object in ()

**Comment by mister-ben** [comment]
Figured out it was because the video.js version range in package.json didn't include 7. Should be ok now in 0.5.2.

**Comment by sbbullet** [comment]
> Figured out it was because the video.js version range in package.json didn't include 7. Should be ok now in 0.5.2.

Updated the version but it's not working. There are no errors on the console but the functions of this plugin are not reflected. The function is executed and all the necessary classes are added as well. But, none of the functions this plugin is required to provide are not being reflected ( neither fullscreen on rotate nor the double-tap to seek). Please, help me out. 

Video JS Version: 7.8.4

videojs-mobile-ui version: 0.5.2

**Comment by bhonrao** [comment]
I am facing the same problem.  Anyone found the solution?  Its not reflecting any functions of mobileui

**Comment by vasaf** [comment]
Same problem... Tried upgrading, downgrading, registering plugin, moving to src folder. No luck

**Comment by sbbullet** [comment]
Did you guys @vasaf @bhonrao  try importing like this?

```
import 'mister-ben/videojs-mobile-ui/dist/videojs-mobile-ui.css';
import videojs from 'video.js';
import 'mister-ben/videojs-mobile-ui';
```

**Comment by mayeaux** [comment]
+1 same issue on React

**Comment by mister-ben** [comment]
To be honest a +1 on a closed issue is unlikely to be noticed at all, and providing no additional information is not helpful.

If you've an issue, instead please log as a new issue **with actionable information** such as a complete minimal example.
