### ISSUE TITLE
In video.js 7, The overlay is not properly inserted before the control bar

### ISSUE THREAD

**Issue by earlpeterg** [mister-ben/videojs-mobile-ui#8]
This makes the control bar unusable on mobile.

![image](https://user-images.githubusercontent.com/26342812/103252879-9905be80-49b9-11eb-9a50-60d7d7a86b93.png)

**Comment by mister-ben** [comment]
I see how this has come back, there's a workaround for a bug in older verisons of 7 and earlier that needs to be removed.

**Comment by earlpeterg** [comment]
Alright. Thanks so much.
